local opt = vim.opt 
opt.number = true
opt.relativenumber = true  
opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.wrap = false
opt.termguicolors = true 
opt.ignorecase = true 
opt.scrolloff = 8
opt.signcolumn = "yes" 
opt.clipboard = "unnamedplus"
